Document: rutorrent
Title: Debian rutorrent Manual
Author: <insert document author here>
Abstract: This manual describes what rutorrent is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rutorrent/rutorrent.sgml.gz

Format: postscript
Files: /usr/share/doc/rutorrent/rutorrent.ps.gz

Format: text
Files: /usr/share/doc/rutorrent/rutorrent.text.gz

Format: HTML
Index: /usr/share/doc/rutorrent/html/index.html
Files: /usr/share/doc/rutorrent/html/*.html
